name: SUB - Build Linux

on:    
  workflow_dispatch:
    inputs:
      env:
        description: 'An Environment'
        required: true
        type: choice
        options:
          - development
          - production
      version:
        description: 'A Version'
        required: true
        type: string

  workflow_call:
    inputs:
      env:
        description: 'An Environment'
        required: true
        type: string
      version:
        description: 'A Version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:    
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Map Env to full-app-name
        uses: spilchen/switch-case-action@v2
        id: full-app-name
        with:
          conditionals-with-values: |
            ${{ inputs.env == 'production' }} => HaxeTemplateApplication
            ${{ inputs.env == 'development' }} => HaxeTemplateApplicationDevelopment
          default: HaxeTemplateApplication

      - name: Test output
        run: echo ${{ steps.full-app-name }}

      - name: Map Env to haxe env flag
        uses: spilchen/switch-case-action@v2
        id: haxe-env-flag
        with:
          conditionals-with-values: |
            ${{ inputs.env == 'production' }} => -final
            ${{ inputs.env == 'development' }} => -debug
          default: -final

      - name: Install missing system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libfuse2

      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Update haxelib
        run: haxelib --global update haxelib --quiet

      - name: Show haxe info
        run: |
          echo "Haxe version:"
          haxe -version
          echo "Haxe lib path:"
          haxelib config

      - name: Install haxelib dependencies
        run: |          
          haxelib install hxcpp --quiet
          haxelib install lime --quiet          
          haxelib install openfl --quiet
          haxelib install actuate --quiet
          haxelib install feathersui --quiet

      - name: Build
        run: haxelib run openfl build project.xml linux ${{ steps.haxe-env-flag.outputs.value }} -clean

      - name: Replace APP_NAME
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: APP_NAME
          replace: ${{ steps.full-app-name.outputs.value }}
          include: build/linux/**

      - name: Replace VERSION
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: VERSION
          replace: ${{ inputs.version }}
          include: build/linux/**

      - name: Make AppDir
        env:
          APP_NAME: ${{ steps.full-app-name.outputs.value }}
        run: |
          mkdir build/linux/${{ env.APP_NAME }}.AppDir
          mkdir build/linux/${{ env.APP_NAME }}.AppDir/usr
          mkdir build/linux/${{ env.APP_NAME }}.AppDir/usr/bin
          mkdir build/linux/${{ env.APP_NAME }}.AppDir/usr/lib

          cp bin/linux/bin/${{ env.APP_NAME }} build/linux/${{ env.APP_NAME }}.AppDir/usr/bin/
          cp bin/linux/bin/lime.ndll build/linux/${{ env.APP_NAME }}.AppDir/usr/lib/lime.ndll
          cp assets/feathersui.svg build/linux/${{ env.APP_NAME }}.AppDir/icon.svg
          cp build/linux/AppRun build/linux/${{ env.APP_NAME }}.AppDir/
          cp build/linux/.desktop build/linux/${{ env.APP_NAME }}.AppDir/        

      - name: Make AppImage
        env:
          APP_NAME: ${{ steps.full-app-name.outputs.value }}
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ./appimagetool-x86_64.AppImage build/linux/${{ env.APP_NAME }}.AppDir
          tree build

      - name: Upload build artifact
        env:
          APP_NAME: ${{ steps.full-app-name.outputs.value }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME }}-Setup.AppImage
          path: ${{ env.APP_NAME }}-x86_64.AppImage
