name: 'Create AppImage'
description: 'Creates an AppImage from binaries and resources'
inputs:
  app-name:
    description: 'Name of the application'
    required: true
  bin-paths:
    description: 'Comma-separated paths to the binaries'
    required: true
  lib-paths:
    description: 'Comma-separated paths to the libraries'
    required: true
  resource-paths:
    description: 'Comma-separated paths to other resources that go into the AppDir'
    required: true
  

runs:
  using: 'composite'
  steps:

    - name: Install dependencies
      run: sudo apt-get install -y libfuse2
      shell: bash

    - name: Download AppImageTool
      run: |
        wget "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
        chmod a+x appimagetool-x86_64.AppImage
      shell: bash

    - name: Create AppDir structure
      run: |
        mkdir -p AppDir/usr/bin
        mkdir -p AppDir/usr/lib

        IFS=',' read -ra ADDR <<< "${{ inputs.bin-paths }}"
        for binary in "${ADDR[@]}"; do 
          cp $binary AppDir/usr/bin; 
        done

        IFS=',' read -ra ADDR <<< "${{ inputs.lib-paths }}"
        for lib in "${ADDR[@]}"; 
          do cp -r $lib AppDir/usr/lib; 
        done

        IFS=',' read -ra ADDR <<< "${{ inputs.resource-paths }}"
        for resource in "${ADDR[@]}"; do 
          cp -r $resource AppDir/; 
        done
      shell: bash

    - name: Debug output
      run: tree AppDir
      shell: bash